#!/usr/bin/env ruby
require 'git/helpers'
require 'optparse'

OptionParser.new do |opts|
  opts.banner = "Git-Helpers git update\n"\
                "Updates the current branch from upstream and pushes the changes to origin\n"\
                'Usage: git update'
  opts.on_tail '-h', '--help', 'Shows this help message' do
    puts opts
    exit 0
  end
  opts.on_tail '-v', '--version', 'Shows the version of git-helpers' do
    puts "Git-Helpers version #{Git::Helpers::VERSION}"
    exit 0
  end
end.parse!

Git::Helpers.update_repository
